apiVersion: v1
kind: ImageStream
metadata:
  labels:
    app: gatling-injector
  name: gatling-injector


---

apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: gatling-injector
  name: gatling-injector
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'gatling-injector:latest'
  source:
    contextDir: /nuxeo-activity-injector
    git:
      ref: master
      uri: 'https://github.com/nuxeo-sandbox/nuxeo-ha-test'
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: 'redhat-openjdk18-openshift:1.1'
        namespace: openshift
    type: Source
  triggers:
    - generic:
        secret: 389c87d4e7825a86
      type: Generic
    - github:
        secret: 20debfb9403339e0
      type: GitHub
    - type: ConfigChange


---


apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gatling-injector
  labels:
    app: gatling-injector
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nuxeo        
    spec:
      containers:
      - name: gatling
        image: docker-registry.default.svc:5000/nuxeo/gatling-injector:latest
        imagePullPolicy: Always
